---
- name: URL Check
  hosts: all

  sources:
    - name: check web site
      ansible.eda.url_check:
        urls:
          - http://abehiroshi.la.coocan.jp
        delay: 60

  rules:
    - name: play JT and debug
      condition: event.url_check.status == "up"
      action:
        - run_job_template:
            name: Demo Job Template
            organization: Default 
        - debug:
            msg: "{{ event }}"
