---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 9999

  rules:
    - name: Say Hello World
      condition: event.payload.message == "Hello"
      action:
        debug:
          msg: Hello World
