---
- name: range
  hosts: all

  sources:
    - ansible.eda.range:
        limit: 5

  rules:
    - name: range events
      condition: event.i > 0
      action:
        debug:
          msg: "{{ event }}"

    - name: shutdown events
      condition: event.i >=3
      action:
        shutdown:
        delay: 0.125
        message: Shutting down after 5 events
