---
- name: URL Check
  hosts: all

  sources:
    - name: check web site
      ansible.eda.url_check:
        urls:
          - http://abehiroshi.la.coocan.jp
        delay: 60

  rules:
    - name: play JT and debug
      condition: event.url_check.status == "up"
      actions:
        - run_job_template:
            name: Demo Job Template
            organization: Default 
        - debug:
            msg: "{{ event }}"

## memo
### {'url_check': {'status_code': 200, 'url': 'http://abehiroshi.la.coocan.jp', 'status': 'up'}, 'meta': {'received_at': '2023-06-29T16:57:15.960849Z', 'source': {'name': 'check web site', 'type': 'ansible.eda.url_check'}, 'uuid': 'c9ce8474-e1a7-47f8-a227-13ae6bfe9b7e'}}
