---
- name: range
  hosts: all

  sources:
    - ansible.eda.range:
        limit: 5

  rules:
    - name: range events
      condition: event.i > 0
      action:
        debug:
          msg: "{{ event }}"
